Add appraisal for rails 6
tests fail with

  NoMethodError:
    undefined method `trigger_transactional_callbacks?' for #<AfterCommitEverywhere::Wrap:0x00007f97c9012f08>
  # ./spec/after_commit_everywhere_spec.rb:303:in `block (4 levels) in <top (required)>'